[package]
name = "emulator"
version = "0.1.0"
edition = "2021"
authors = ["OpenSauce"]
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = { version = "1.0", default-features = false }
